---
- hosts: all
  tasks:
    - git:
        repo: 'https://github.com/VundleVim/Vundle.vim.git'
        dest: ~/.vim/bundle/Vundle.vim
    - name: copy vimrc
      copy: src=files/vimrc dest=~/.vimrc

